services:
  koombea_web_scraper:
    stdin_open: true
    tty: true
    build: .
    container_name: koombea_web_scraper
    command: iex -S mix phx.server
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13.5
    container_name: koombea_web_scraper_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: koombea_web_scraper_dev
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
